/**
 * Loads pre-computed campus metrics once at page load and caches them
 * module-level so subsequent calls get the data instantly.
 *
 * Generated by:  npm run precompute
 * File:          public/data/campus_metrics.json
 * Refreshed:     daily (build-time or cron)
 */

import { useState, useEffect } from 'react';

let _cache = null;
let _promise = null;

function fetchOnce() {
  if (_cache) return Promise.resolve(_cache);
  if (!_promise) {
    _promise = fetch('/data/campus_metrics.json')
      .then(r => r.json())
      .then(d => { _cache = d; return d; })
      .catch(() => { _promise = null; return null; });
  }
  return _promise;
}

function pickStats(d) {
  if (!d) return null;
  return {
    campusCount:      d.campus_count ?? null,
    totalCampusCount: d.total_campus_count ?? null,
    noOperatorCount:  d.no_operator_count ?? null,
    noOperatorPct:    d.no_operator_pct ?? null,
    totalPowerMW:     d.total_power_mw ?? null,
  };
}

/**
 * Returns `{ metrics, stats, generatedAt, loading }`.
 * `metrics` is a map of campus_id → { power_mw, total_mwh_yr, pue, pue_reported, dc_type, … }
 * `stats`   is dataset-wide counts used by the UI so displayed figures never drift.
 */
export function useCampusPower() {
  const [state, setState] = useState(() => ({
    metrics: _cache?.campuses ?? null,
    stats: pickStats(_cache),
    generatedAt: _cache?.generated_at ?? null,
    loading: !_cache,
  }));

  useEffect(() => {
    if (_cache) return;
    fetchOnce().then(d => {
      if (!d) return;
      setState({ metrics: d.campuses, stats: pickStats(d), generatedAt: d.generated_at, loading: false });
    });
  }, []);

  return state;
}

/** Direct accessor for a single campus (returns null when not yet loaded). */
export function getCampusMetrics(campusId) {
  return _cache?.campuses?.[campusId] ?? null;
}
